#import "../../lib/mod.typ": *

== Motivation <intro-motivation>

// From the original contract:
// 1. Motivation
// Automation is constantly increasing, and multi-agent systems are proportionally relevant. Many current-day systems, such as the agriculture industry[1], along with many other fields, are on a trajectory toward autonomous multi-agent robotics. This trend can also be projected onto more mainstream everyday tasks, such as manual transportation. The adoption of autonomous vehicles is increasing, and the technology is becoming more and more mature. As the fraction of autonomous vehicles increases, the possibilities for efficient traffic expand exponentially with the ability to coordinate and communicate between vehicles. For such systems to reach their full potential, it is preferred to move at high speeds and ensure deadlocks are avoided. This is especially relevant in scenarios where the room for movement is limited, this could be an indoor environment or roads with specific boundaries. Overall, putting effort towards the development of the multi-agent field will help enable many current and future systems to do more in less time, and with fewer resources.

// Along with an increase in automation comes a paradigm shift in the design space, which in turn gives room for systems of higher complexity.

// Step 1: Explain the broad scale of the motivation
Harnessing the power of automation has been a key driver for the long term development of human manufacturing and quality of life in the modern world since the Industrial Revolution. As automation advances, it paves the way for autonomous systems to reach higher levels of complexity, with more degrees of freedom.@schwabe_automation_2020@mit_industrial_2024 Many current-day systems, such as the agriculture industry@wisse_wp1_2020 are on a trajectory toward autonomous multi-agent robotics. This trend can also be projected onto more mainstream everyday tasks, such as manual transportation. The adoption of autonomous vehicles is increasing, and the technology is becoming more and more mature. As the fraction of autonomous vehicles increases, the possibilities for efficient traffic expand exponentially with the ability to coordinate and communicate between vehicles. For such systems to reach their full potential, it is preferred to move at high speeds and ensure that deadlocks are avoided. This is especially relevant in scenarios where the room for movement is limited, this could be an indoor environment or roads with specific boundaries. Overall, putting effort towards the development of the multi-agent field will help enable many current and future systems to do more in less time, and with fewer resources.

// Step 2: Explain how the broad scale applies to the specific motivation of multi-agent systems
With this development, the possibility and thus also demand for multi-agent systems have become much more prevalent. This is especially impacting the field of robotics, where separate agents can work together to achieve a common goal, or even work together to achieve separate goals as efficiently as possible.

// Step 3: Connect that to the specific problem of path planning, collaboration, communication, and collision avoidance
In the context of multi-agent systems, path planning is a key component. It is a process of optimization to find the most efficient path for an agent to reach its goal. This is especially important in the context of multi-agent systems, where multiple agents need to coordinate their movements to avoid collisions and reach their goals as efficiently as possible. This requires a high level of collaboration and communication between the agents, as well as a high level of collision avoidance to ensure that the agents do not collide with each other or with obstacles.
